# This file was generated by nais/device. DO NOT EDIT.
cask "naisdevice-tenant" do
  version "v1.3.0"
  name "naisdeice-tenant"
  desc "naisdevice is a mechanism enabling developers to connect to internal resources in a secure and friendly manner."
  homepage "https://docs.nais.io/operate/naisdevice/how-to/install/"

  depends_on formula: [
    "wireguard-go",
    "wireguard-tools",
  ]

  if Hardware::CPU.intel?
    url "https://github.com/nais/device/releases/download/v1.3.0/naisdevice-tenant_macos_amd64.pkg", verified: "github.com/nais/device/"
    sha256 "BFCD69195E42C6F1D39C315E066C1E450910E30C2DF0DFFB20062983F91A26DF"
    pkg "naisdevice-tenant_macos_amd64.pkg"
  end
  if Hardware::CPU.arm?
    url "https://github.com/nais/device/releases/download/v1.3.0/naisdevice-tenant_macos_arm64.pkg", verified: "github.com/nais/device/"
    sha256 "37278871CA9563405337A1DF68E2598866114EEB673E521B14A92B1C2E7B6F33"
    pkg "naisdevice-tenant_macos_arm64.pkg"
  end

  uninstall pkgutil: "io.nais.device"
end
