# This file was generated by nais/device. DO NOT EDIT.
cask "naisdevice-tenant" do
  version "v1.4.1"
  name "naisdeice-tenant"
  desc "naisdevice is a mechanism enabling developers to connect to internal resources in a secure and friendly manner."
  homepage "https://docs.nais.io/operate/naisdevice/how-to/install/"

  depends_on formula: [
    "wireguard-go",
    "wireguard-tools",
  ]

  if Hardware::CPU.intel?
    url "https://github.com/nais/device/releases/download/v1.4.1/naisdevice-tenant_macos_amd64.pkg", verified: "github.com/nais/device/"
    sha256 "9EDD894CC0580BD63B2D90D0FF1FDDA3443060AAB74FCC10FBD9D22EC473B135"
    pkg "naisdevice-tenant_macos_amd64.pkg"
  end
  if Hardware::CPU.arm?
    url "https://github.com/nais/device/releases/download/v1.4.1/naisdevice-tenant_macos_arm64.pkg", verified: "github.com/nais/device/"
    sha256 "7E4F3744269094C83CF3956F70F13B04BD3E9CA58F4F26EF87FAB669697003F7"
    pkg "naisdevice-tenant_macos_arm64.pkg"
  end

  uninstall pkgutil: "io.nais.device"
end
