# This file was generated by nais/device. DO NOT EDIT.
cask "naisdevice-tenant" do
  version "v1.14.5"
  name "naisdeice-tenant"
  desc "naisdevice is a mechanism enabling developers to connect to internal resources in a secure and friendly manner."
  homepage "https://docs.nais.io/operate/naisdevice/how-to/install/"

  depends_on formula: [
    "wireguard-go",
    "wireguard-tools",
  ]

  if Hardware::CPU.intel?
    url "https://github.com/nais/device/releases/download/#{version}/naisdevice-tenant_macos_amd64.pkg", verified: "github.com/nais/device/"
    sha256 "CB9CFBA20EB5B489D8626122F31D9B14C684E2D1653997BB9EAA52B07A991A3E"
    pkg "naisdevice-tenant_macos_amd64.pkg"
  end
  if Hardware::CPU.arm?
    url "https://github.com/nais/device/releases/download/#{version}/naisdevice-tenant_macos_arm64.pkg", verified: "github.com/nais/device/"
    sha256 "1C40D939AC331D472919A37929B8E485EA151E0A4A26B4131EC91FDF1520A6E0"
    pkg "naisdevice-tenant_macos_arm64.pkg"
  end

  uninstall pkgutil: "io.nais.device"
end
