# This file was generated by nais/device. DO NOT EDIT.
cask "naisdevice" do
  version "v1.10.4"
  name "naisdevice"
  desc "naisdevice is a mechanism enabling developers to connect to internal resources in a secure and friendly manner."
  homepage "https://docs.nais.io/operate/naisdevice/how-to/install/"

  depends_on formula: [
    "wireguard-go",
    "wireguard-tools",
  ]

  if Hardware::CPU.intel?
    url "https://github.com/nais/device/releases/download/v1.10.4/naisdevice_macos_amd64.pkg", verified: "github.com/nais/device/"
    sha256 "91637CB56F6191E1F032DA60C61313B085F1F7C2C02C3DDEA51D6138F8236CE1"
    pkg "naisdevice_macos_amd64.pkg"
  end
  if Hardware::CPU.arm?
    url "https://github.com/nais/device/releases/download/v1.10.4/naisdevice_macos_arm64.pkg", verified: "github.com/nais/device/"
    sha256 "B89CAEE9CCB3A9780D2A5BF5CE49BC942AAF5F7076F22E62B8EBAE92116FB410"
    pkg "naisdevice_macos_arm64.pkg"
  end

  uninstall pkgutil: "io.nais.device"
end
