# This file was generated by nais/device. DO NOT EDIT.
cask "naisdevice" do
  version "v1.5.0"
  name "naisdevice"
  desc "naisdevice is a mechanism enabling developers to connect to internal resources in a secure and friendly manner."
  homepage "https://docs.nais.io/operate/naisdevice/how-to/install/"

  depends_on formula: [
    "wireguard-go",
    "wireguard-tools",
  ]

  if Hardware::CPU.intel?
    url "https://github.com/nais/device/releases/download/v1.5.0/naisdevice_macos_amd64.pkg", verified: "github.com/nais/device/"
    sha256 "AE2BD03C173BD03BEB7A7CF5F9A14B12BC32615192E4EF129F4A753C514EA7BA"
    pkg "naisdevice_macos_amd64.pkg"
  end
  if Hardware::CPU.arm?
    url "https://github.com/nais/device/releases/download/v1.5.0/naisdevice_macos_arm64.pkg", verified: "github.com/nais/device/"
    sha256 "9FF7064A0B15DEEFC36EC55F165756352A5B8E2F81D9C8B8C4AC718493726CA0"
    pkg "naisdevice_macos_arm64.pkg"
  end

  uninstall pkgutil: "io.nais.device"
end
