# This file was generated by nais/device. DO NOT EDIT.
cask "naisdevice" do
  version "v1.0.7"
  name "naisdevice"
  desc "naisdevice is a mechanism enabling developers to connect to internal resources in a secure and friendly manner."
  homepage "https://docs.nais.io/operate/naisdevice/how-to/install/"

  if Hardware::CPU.intel?
    url "https://github.com/nais/device/releases/download/v1.0.7/naisdevice_macos_amd64.pkg"
    sha256 "F6944926A4CD589C9C42720BB40131D701A84F58720BE6BEFC938D283B19FA24"
    pkg "naisdevice_macos_amd64.pkg"
  end
  if Hardware::CPU.arm?
    url "https://github.com/nais/device/releases/download/v1.0.7/naisdevice_macos_arm64.pkg"
    sha256 "EFFC6D9332D746036D34AB79365270DD90CECB4586A92633B411F4EABCB51375"
    pkg "naisdevice_macos_arm64.pkg"
  end

  uninstall pkgutil: "io.nais.device"
end
