# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debuk < Formula
  desc "Simple Aiven Kafka Debug Cli"
  homepage "https://github.com/nais/debuk"
  version "0.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nais/debuk/releases/download/v0.0.1/debuk_0.0.1_darwin_amd64.tar.gz"
      sha256 "46808f3387ac79cec5229e9fff9ba8f83734f988fa8718b14c1fa8ed1e7f7dd1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nais/debuk/releases/download/v0.0.1/debuk_0.0.1_darwin_arm64.tar.gz"
      sha256 "44e2e30f556833b77446c5f01be8f8966aff7c9c7a4279f94ae4964aaec801bb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nais/debuk/releases/download/v0.0.1/debuk_0.0.1_linux_amd64.tar.gz"
      sha256 "2c95646b2554b3f6a3fda1ef14e54f48e6fa4972e5d8f07883528b452c78b47e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nais/debuk/releases/download/v0.0.1/debuk_0.0.1_linux_arm64.tar.gz"
      sha256 "f46fa22b10394887ba01d9d553c70ed546282ed6139d9e493d8c2d09a6670463"
    end
  end

  def install
    bin.install "debuk"
  end

  test do
    assert_match version, shell_output("#{bin}/debuk version")
  end
end
