# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debuk < Formula
  desc "Simple Aiven Kafka Debug Cli"
  homepage "https://github.com/nais/debuk"
  version "0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nais/debuk/releases/download/v0.1/debuk_cli_0.1_darwin_amd64.tar.gz"
      sha256 "d704287ffeec00dd4ae2bf7c47e04d55b42fafd0e33d0dbf73eb9ca237fbdba4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nais/debuk/releases/download/v0.1/debuk_cli_0.1_darwin_arm64.tar.gz"
      sha256 "1af9c1e12331b96a5c7c94295ba9afdfa87ceb7f097412b6a016ffe710a3c64a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nais/debuk/releases/download/v0.1/debuk_cli_0.1_linux_amd64.tar.gz"
      sha256 "5846ca2d39496146439b23d56a3ad9ddef04ab317506d903515e464c2e3e5121"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nais/debuk/releases/download/v0.1/debuk_cli_0.1_linux_arm64.tar.gz"
      sha256 "72094ed606448286e053d61d721691c390d98707f0119c033226e51ba80c91e9"
    end
  end

  def install
    bin.install "debuk"
  end

  test do
    assert_match / Debuk is a CLI./ , shell_output("#{bin}/debuk -h")
  end
end
