# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debuk < Formula
  desc "Simple Aiven Kafka Debug Cli"
  homepage "https://github.com/nais/debuk"
  version "0.0.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nais/debuk/releases/download/v0.0.2/debuk_0.0.2_darwin_amd64.tar.gz"
      sha256 "ba4833ca239a70f0ff569aca6ed8f7e8214a0bcde5c4e2fbf26d3a74c22f782e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nais/debuk/releases/download/v0.0.2/debuk_0.0.2_darwin_arm64.tar.gz"
      sha256 "893279c741da1a8115826f13895a9b5d677913d91223a1ed8bad6b05c73724d3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nais/debuk/releases/download/v0.0.2/debuk_0.0.2_linux_amd64.tar.gz"
      sha256 "705a422e3dbe3b22360becfc5e47dd504bdeb546ad00470a2691f41e282d772e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nais/debuk/releases/download/v0.0.2/debuk_0.0.2_linux_arm64.tar.gz"
      sha256 "400820377fdcf88fee2592061433ab2b6a2aca817f5270f6de7a72e940d4dabb"
    end
  end

  def install
    bin.install "debuk"
  end

  test do
    assert_match version, shell_output("#{bin}/debuk version")
  end
end
