# frozen_string_literal: true

# This file was generated by nais/cli. DO NOT EDIT.
class Nais < Formula
  desc "Command-line interface for Nais"
  homepage "https://github.com/nais/cli"
  version "5.21.0"
  version_scheme 1

  on_macos do
    on_intel do
      url "https://github.com/nais/cli/releases/download/v5.21.0/nais-cli_darwin_amd64.tgz"
      sha256 "225ec684b3168bc9ac90852526b567be32798b2c43d8ab5129e2b3d81ef9707f"
    end
    on_arm do
      url "https://github.com/nais/cli/releases/download/v5.21.0/nais-cli_darwin_arm64.tgz"
      sha256 "5495302e96944b4ff5e125f7a0c00ef1c180d53db8d9213a24f9cd080c24004e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nais/cli/releases/download/v5.21.0/nais-cli_linux_amd64.tgz"
      sha256 "6a0e72166162f381ff5b76853d00bfef8c58a6cf6cd0989af96ac4e6d3e3494c"
    end
    on_arm do
      url "https://github.com/nais/cli/releases/download/v5.21.0/nais-cli_linux_arm64.tgz"
      sha256 "6733a808c386b09fd9b06434afd46cbe4ed4dedf479792eab42cad5e9b793c03"
    end
  end

  def install
    bin.install "nais"
    bash_completion.install "completions/nais.bash" => "nais"
    zsh_completion.install "completions/nais.zsh" => "_nais"
    fish_completion.install "completions/nais.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nais --version")
  end
end
