# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nais < Formula
  desc "Simple Aiven Kafka Debug Cli"
  homepage "https://github.com/nais/nais-cli"
  version "1.20210922.121842"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nais/nais-cli/releases/download/1.20210922.121842/nais-cli_1.20210922.121842_darwin_amd64.tar.gz"
      sha256 "01d53d51c45895823c1c02d23d2bca470fe3eace23a4d123976f560b95089d1b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nais/nais-cli/releases/download/1.20210922.121842/nais-cli_1.20210922.121842_darwin_arm64.tar.gz"
      sha256 "b4e6460ec757fc28a0aecd3fd5a26733efafb8398fc645dea3c07f31f8028557"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nais/nais-cli/releases/download/1.20210922.121842/nais-cli_1.20210922.121842_linux_amd64.tar.gz"
      sha256 "56390a5546b8de92017025f237e918a3493ccbb4e4533722fc1f7e2ed96a987f"
    end
  end

  def install
    bin.install "nais"
  end

  test do
    assert_match version, shell_output("#{bin}/nais version")
  end
end
