# typed: false
# frozen_string_literal: true

# This file was generated by nais/narcos. DO NOT EDIT.
class Narc < Formula
  desc "Admin command-line interface for Nais"
  homepage "https://github.com/nais/narcos"
  version "v2.1.6"
  version_scheme 1

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nais/narcos/releases/download/v2.1.6/narc-cli_v2.1.6_darwin_amd64.tar.gz"
      sha256 "64757313489a932145c6cb6ec7ccd6703195369cdb1f822d2bca205ad516ff35"

      def install
        bin.install "narc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nais/narcos/releases/download/v2.1.6/narc-cli_v2.1.6_darwin_arm64.tar.gz"
      sha256 "b9b1663c692499dd9bc13af0c2b2576445af32ac6b1931e38430bad8412ef5d5"

      def install
        bin.install "narc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nais/narcos/releases/download/v2.1.6/narc-cli_v2.1.6_linux_amd64.tar.gz"
      sha256 "2f6b3728f2cb3565139a18d5d6e26271c8e1608df2a448d3cd7e876252087604"
      def install
        bin.install "narc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nais/narcos/releases/download/v2.1.6/narc-cli_v2.1.6_linux_arm64.tar.gz"
      sha256 "68bc7890b8d82d7786a9eccbaaa08763df257fd90cdd37aa1908d5a4bc121d44"
      def install
        bin.install "narc"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/narc version")
  end
end
