# typed: false
# frozen_string_literal: true

# This file was generated by nais/narcos. DO NOT EDIT.
class Narc < Formula
  desc "Admin command-line interface for Nais"
  homepage "https://github.com/nais/narcos"
  version "v2.3.3"
  version_scheme 1

  on_macos do
    on_intel do
      url "https://github.com/nais/narcos/releases/download/v2.3.3/narc-cli_darwin_amd64.tgz"
      sha256 "503643F874418F7600460C32B79FBD6B92AA8EFB070AE4E3BE0BEC20D8AC2132"
    end
    on_arm do
      url "https://github.com/nais/narcos/releases/download/v2.3.3/narc-cli_darwin_arm64.tgz"
      sha256 "3D1A830E83E01E84FCE38AC083E8BA003F8F0C8691D7BE39B53794A2A91D1C3E"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nais/narcos/releases/download/v2.3.3/narc-cli_linux_amd64.tgz"
      sha256 "F4200AD0C2268D6CE704DD825E313B3334B96C967DEB7DE2A4EFF2BFF5846335"
    end
    on_arm do
      url "https://github.com/nais/narcos/releases/download/v2.3.3/narc-cli_linux_arm64.tgz"
      sha256 "5FE20E6D6E17911CDE8895046CE991FBA2B08181E9160EACFF1CCFBD98CB3A58"
    end
  end

  def install
    bin.install "narc"
  end

  test do
    assert_match version, shell_output("#{bin}/narc version")
  end
end
