# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Narc < Formula
  desc "NAIS Administration CLI"
  homepage "https://github.com/nais/narcos"
  version "1.20241023134531"

  on_macos do
    on_intel do
      url "https://github.com/nais/narcos/releases/download/1.20241023134531/narc-cli_1.20241023134531_darwin_amd64.tar.gz"
      sha256 "670e56d6507440769b040fe632fac18aeeed65a94f39f7c3dd3bf9988a04a8d4"

      def install
        bin.install "narc"
      end
    end
    on_arm do
      url "https://github.com/nais/narcos/releases/download/1.20241023134531/narc-cli_1.20241023134531_darwin_arm64.tar.gz"
      sha256 "5646c0321766d01268d1e7242c5fb3a0b1ee5a88d55ac9c28fd0dde2e2534e6e"

      def install
        bin.install "narc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nais/narcos/releases/download/1.20241023134531/narc-cli_1.20241023134531_linux_amd64.tar.gz"
        sha256 "2f5ee0800481b7e01322769e1b365c88d7641ac5d841bac5e71792776b216835"

        def install
          bin.install "narc"
        end
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/narc version")
  end
end
