# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Salsa < Formula
  desc "Command-line interface for SLSA provenance"
  homepage "https://github.com/nais/salsa"
  version "0.1.20220429081148"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nais/salsa/releases/download/v0.1.20220429081148/nais-salsa_0.1.20220429081148_darwin_arm64.tar.gz"
      sha256 "e089d9520e7287c19fa7c3c267ab2721dc0bb26bd62ec89eecb3e6bda93fa9b5"

      def install
        bin.install "salsa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nais/salsa/releases/download/v0.1.20220429081148/nais-salsa_0.1.20220429081148_darwin_amd64.tar.gz"
      sha256 "e03db7f45ee50960d1bc8d2c7fc409104e6bb384e6419b321d97c976f3bbfe6c"

      def install
        bin.install "salsa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nais/salsa/releases/download/v0.1.20220429081148/nais-salsa_0.1.20220429081148_linux_amd64.tar.gz"
      sha256 "77045a3b5ed5064dfec812ef3977c217ebf7c15580bd99442999fd51107dcc8b"

      def install
        bin.install "salsa"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/salsa version")
  end
end
