# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Salsa < Formula
  desc "Command-line interface for SLSA provenance"
  homepage "https://github.com/nais/salsa"
  version "0.1.20220324122739"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nais/salsa/releases/download/0.1.20220324122739/nais-salsa_0.1.20220324122739_darwin_arm64.tar.gz"
      sha256 "dcc15332e58744b02e6fbcc448b6f53422b8c1422b98fbe383fe547fe2669651"

      def install
        bin.install "salsa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nais/salsa/releases/download/0.1.20220324122739/nais-salsa_0.1.20220324122739_darwin_amd64.tar.gz"
      sha256 "38c7ff29a1264adabccbbef63da52be1ecc3be413eed70bab810fd55200fc7ac"

      def install
        bin.install "salsa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nais/salsa/releases/download/0.1.20220324122739/nais-salsa_0.1.20220324122739_linux_amd64.tar.gz"
      sha256 "dde92fc986adce62b5c89c6fdcbac24a1e051df22583f34816a6d7b8994afe69"

      def install
        bin.install "salsa"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/salsa version")
  end
end
