name: Brew Test Bot

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"

  pull_request:
    paths:
      - "Formula/**"
      - "Casks/**"

jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Homebrew
        run: brew update

      - name: Run brew test-bot
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew tap --force-auto-update $GITHUB_REPOSITORY .
          brew test-bot --tap=$GITHUB_REPOSITORY
