name: Brew Test Bot
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
  pull_request:

jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - run: brew update
      - env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: brew tap $GITHUB_REPOSITORY .
      - env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: brew test-bot --tap=$GITHUB_REPOSITORY
